### ISSUE TITLE
Collections doesn't work

### ISSUE THREAD

**Issue by sauliusgrigaitis** [kylef/Stencil#51]
Output of example https://github.com/kylef/Stencil#example on Linux is:
```
There are  articles.



```

**Comment by sauliusgrigaitis** [comment]
@kylef how can I run Stencil tests on Linux, so I can check does it pass.

**Comment by kylef** [comment]
I've made some changes which allow running the tests on Linux via `make test`. Unfortunately running a little short on time to be able to solve the linux problems at the moment. I have however made a `linux` branch which adds CI for Linux.

I would assume the problem lies in https://github.com/kylef/Stencil/blob/master/Sources/Variable.swift#L50, I'll try dive into it one evening.

**Comment by sauliusgrigaitis** [comment]
Thanks @kylef , but tests still doesn't work on Linux with ```swift-DEVELOPMENT-SNAPSHOT-2016-02-03-a-ubuntu15.10```:
```
$ make test
Building Stencil
Running Tests
Tests/VariableSpec.swift:6:2: error: only classes that inherit from NSObject can be declared @objc
@objc class Object : NSObject {
~^~~~~
InvocationError()
Makefile:6: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by kylef** [comment]
Right, I've disabled the KVO handling in the `kylef/linux` branch which allows the tests to run on linux, there are 10 failing tests related to array and dictionary handling. The problem is entirely in [resolveArray](https://github.com/kylef/Stencil/blob/master/Sources/Variable.swift#L116) where trying to turn array into [Any] fails completely, this seems like a Swift bug.

Here's an example (the `it works` message is not shown):

```swift
let items = [1, 2, 3] as Any

if let items = items as? [Any] { 
  print("it works") 
} 
```

**Comment by matteocrippa** [comment]
hey @kylef I was looking at this issue, seems pretty related to [this](http://stackoverflow.com/questions/32156910/swift-pattern-match-on-arrayany)

**Comment by ketzusaka** [comment]
I was asking around about this and got this:

[12:09:18]  <mikeash>	unfortunately the concept of an arbitrary Array doesn't exist in Swift
[12:09:54]  <mikeash>	generic types always have concrete associated types, there's no conceptual supertype where they're left unspecified

**Comment by dileping** [comment]
@kylef In [Express](https://github.com/crossroadlabs/Express) we have a workaround for this.
Take a look at this file: [StencilViewEngine.swift](https://github.com/crossroadlabs/Express/blob/develop/Express/StencilViewEngine.swift)
May be it will give you an insight on how to better fix it inside Stencil.

**Comment by kylef** [comment]
Thanks for the pointers @dileping, managed to get that solution working and the tests on master are now running and passing on CI for both OS X and Linux.

This has been fixed and released as 0.5.3.

**Comment by dileping** [comment]
@kylef You are welcome ;)

**Comment by dileping** [comment]
And thanks a lot for your hard work on Stencil
